// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA4l-S6yhpwt20NiIWcNogZ59pYVkvM6E',
    appId: '1:275370982626:web:0f5271e8a69eba9297b2bb',
    messagingSenderId: '275370982626',
    projectId: 'wellness-hub-platform',
    authDomain: 'wellness-hub-platform.firebaseapp.com',
    storageBucket: 'wellness-hub-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCswl1KtuejVOEPoINTS34E-g9qXRJYP4M',
    appId: '1:275370982626:android:f29125fa8ddec2e497b2bb',
    messagingSenderId: '275370982626',
    projectId: 'wellness-hub-platform',
    storageBucket: 'wellness-hub-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_-Z-FkCa6Fo1JjBAeAh9rzaSUeg7jFWo',
    appId: '1:275370982626:ios:ac37a904f679f8cc97b2bb',
    messagingSenderId: '275370982626',
    projectId: 'wellness-hub-platform',
    storageBucket: 'wellness-hub-platform.firebasestorage.app',
    iosBundleId: 'com.example.uxGlass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_-Z-FkCa6Fo1JjBAeAh9rzaSUeg7jFWo',
    appId: '1:275370982626:ios:3e71d82cbc2f071e97b2bb',
    messagingSenderId: '275370982626',
    projectId: 'wellness-hub-platform',
    storageBucket: 'wellness-hub-platform.firebasestorage.app',
    iosBundleId: 'com.example.wellnessHubFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA4l-S6yhpwt20NiIWcNogZ59pYVkvM6E',
    appId: '1:275370982626:web:0f5271e8a69eba9297b2bb',
    messagingSenderId: '275370982626',
    projectId: 'wellness-hub-platform',
    authDomain: 'wellness-hub-platform.firebaseapp.com',
    storageBucket: 'wellness-hub-platform.firebasestorage.app',
  );

}