// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Ensure this file is generated by flutterfire_cli

import 'splash_screen.dart';
import 'login_screen.dart';
import 'main_screen.dart'; // This is where your BottomNav and HomeScreen are managed

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Wellness Hub',
      theme: ThemeData(
        primarySwatch: Colors.purple,
        scaffoldBackgroundColor: const Color(0xFFF3E5F5), // Main light purple
        fontFamily: 'Inter',
        appBarTheme: AppBarTheme(
          backgroundColor: Colors.purple[400], // A distinct, richer purple for AppBar
          elevation: 4,
          iconTheme: const IconThemeData(color: Colors.white70),
          actionsIconTheme: const IconThemeData(color: Colors.white),
          titleTextStyle: const TextStyle(
            color: Colors.white,
            fontSize: 20,
            fontWeight: FontWeight.bold,
            fontFamily: 'Inter',
          ),
        ),
      ),
      // --- CRITICAL FOR INITIAL FLOW ---
      initialRoute: '/splash',
      routes: {
        '/splash': (context) => const SplashScreen(),
        '/login': (context) => const LoginScreen(),
        '/home': (context) => const MainScreen(), // MainScreen now acts as the entry to your dashboard
      },
      // --- END CRITICAL SECTION ---
    );
  }
}