# coding: utf-8

"""
    Body Service API

    API for delivering wellness content related to Body (e.g., Yoga videos, exercise routines).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Body Service API",
    description="API for delivering wellness content related to Body (e.g., Yoga videos, exercise routines).",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
